server:
  port: 443
  ssl:
    key-store: src\main\resources\star.scery.com.jks
    key-password: 123456
    key-store-type: JKS


spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pinche2?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    dbcp2:
      test-while-idle: true
    tomcat:
      test-while-idle: false

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:static/*.xml,classpath*:static/*.xml
  type-aliases-package: com.pin.chen
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true